Hi! I was told by 
@graham
 to coordinate with you for my program, Hackclub Webspaces to get it added! (edited) 
5:15
I made a demo at https://spaces.learnwillow.org btw








Ethan
:orphmoji-yay:  9:26 PM
How should I contact you? Via email or slack?


msw
  9:58 PM
This is awesome!


Ethan
:orphmoji-yay:  9:58 PM
hi!!!!!
9:58
Did ya check it out??


msw
  10:02 PM
Checking it out now
:thumbsup-dino:
1

10:03
Can I see some repos created with it?


Ethan
:orphmoji-yay:  10:03 PM
I am currently working on git integration atm but you can create and share projects on the app
10:04
Btw if it asks for a preview code when signing up
10:04
use iloveboba
10:04
its to prevent ppl from messing it up when i'm making it


Ethan
:orphmoji-yay:  10:38 PM
Well, thanks for looking at it! Looking forward to add more!


msw
  7:23 AM
I’d love to get this used in club meetings for people who don’t have full access to their own computer
7:23
Ie. Chromebook that can’t install vs code
7:24
But it needs git operations for that


Ethan
:orphmoji-yay:  9:13 AM
Makes sense! I’ll work on getting that added! Thanks for the feedback!
9:17
I’ll let ya know when I get that added


Ethan
:orphmoji-yay:  10:56 AM
By the way, I want to add more to it (regardless if it gets added to HackClub or not). Anything I can improve?


Ethan
:orphmoji-yay:  12:30 PM
I got git integration to work!!!! (took me a while but did it!). In the project, users just need to click the "Git" button to automatically create/push changes to a repo.


Ethan
:orphmoji-yay:  1:20 PM
image.png
 
image.png


Ethan
:orphmoji-yay:  3:21 PM
https://github.com/EthanJCanterbury/spaces
ready for you to review!

EthanJCanterbury/spaces
Language
CSS
Last updated
4 minutes ago
Added by GitHub


Ethan
:orphmoji-yay:  6:34 PM
Bombarding you with messages today! Sorry! Here's a demo video of everything.
HackClub Spaces - Static Website Hosting.mp4
 


Ethan
:orphmoji-yay:  6:11 PM
Hi! Just talked to 
@jps
 and 
@Rushmore (Rrr)
, thought I should share this with you as well!
https://docs.google.com/document/d/1vikyMtCiDX2AinjqWdmRpkjAF1eO-4ZrlmQqNzZfFBA/edit?usp=sharing

Google Docs
 

Hack Club Spaces (Beta) Notes
Google Doc


msw
  11:09 AM
this looks great! I'll try it out later today
11:09
ah, is there any version of this i can use without the private & delete perms?
Screenshot 2025-03-14 at 11.08.49.png
 
Screenshot 2025-03-14 at 11.08.49.png


Ethan
:orphmoji-yay:  2:27 PM
Yeah sure! Sign up with normal auth and use code iloveboba (just git won’t work)


msw
  10:19 PM
here's the spaces db url: postgres://postgres:GhvyWgpWdigdiwRmJ5gngVJ6U49Y8AiDauwsXnjfNNc1XCRIZEDHHs3uZvdhQJC1@k8c4kw84c88kkgwo4gkkk4k4:5432/postgres?sslmode=require


Ethan
:orphmoji-yay:  10:19 PM
any user or password?


Ethan
:orphmoji-yay:  6:08 PM
{
  "DATABASE_URL": "postgresql://neondb_owner:npg_zyvpAYX5oi0k@ep-ancient-hill-a6yb7my6.us-west-2.aws.neon.tech/neondb?sslmode=require",
  "PGDATABASE": "neondb",
  "PGHOST": "ep-ancient-hill-a6yb7my6.us-west-2.aws.neon.tech",
  "PGPORT": "5432",
  "PGUSER": "neondb_owner",
  "PGPASSWORD": "npg_zyvpAYX5oi0k",
  "GITHUB_CLIENT_ID": "Ov23liPtaMsNRLw66vxr",
  "GITHUB_CLIENT_SECRET": "6727f41bec7ddeef2d0fe2638b0cb7780fa84706",
  "SLACK_CLIENT_ID": "2210535565.8465855857699",
  "SLACK_CLIENT_SECRET": "3bc9cf4b47843d2157255e0f4eb0f44c",
  "SLACK_REDIRECT_URI": "https://spaces.learnwillow.org/api/slack/callback",
  "GITHUB_CALLBACK_URL": "https://spaces.hackclub.com/api/github/callback",
  "GROQ_API_KEY": "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"
}
(the db details are for the old db which we are still using atm, i'll switch everything over to the new db once we get everything running on coolify)


msw
  6:58 PM
You should set up the coolify db now while we wait!


Ethan
:orphmoji-yay:  6:59 PM
Alright! I'll work on that, just gotta finish some styling issues first


msw
  7:00 PM
Styling?! It’s not in prod!
7:00
There’s a pyramid of needs to an app


Ethan
:orphmoji-yay:  7:00 PM
yeah but its really bugging me


msw
  7:01 PM
It’d be weird for someone to worry about nail polish if they havent eaten in 3 weeks


Ethan
:orphmoji-yay:  7:01 PM
alr i'll work on db


Ethan
:orphmoji-yay:  7:10 PM
postgres://postgres:GhvyWgpWdigdiwRmJ5gngVJ6U49Y8AiDauwsXnjfNNc1XCRIZEDHHs3uZvdhQJC1@k8c4kw84c88kkgwo4gkkk4k4:5432/postgres?sslmode=require
the psql link you gave me doesnt seem to have a domain
7:10
(so its invalid)


msw
  8:32 PM
sorry, that's an internal domain– this is the sql database your prod app can access but isn't accessible outside of that
:upvote:
1

8:32
i'll get you a public url shortly
:sparkling_heart:
1

8:34
postgres://postgres:GhvyWgpWdigdiwRmJ5gngVJ6U49Y8AiDauwsXnjfNNc1XCRIZEDHHs3uZvdhQJC1@5.161.100.52:9846/postgres
8:35
i also just restarted the instance, so you might need to give it a minute
:+1:
1



Ethan
:orphmoji-yay:  8:35 PM
awesome! Let me get that migrated :D


msw
  8:36 PM
your prod env doesn't seem like what you want it to be
8:37
for starters, that's a json, but also things like SLACK_REDIRECT_URI should probably be at spaces.hackclub.com
8:37
also, redirect uri probably shouldn't be in the env?
8:37
this is mostly for secrets, and that doesn't seem like a secret thing


Ethan
:orphmoji-yay:  8:38 PM
Yeah i just used it when quickly switching domains since a .env was easier for me to edit quickly
8:38
i'll look at it though


msw
  8:38 PM
gotcha- send me the file you want me to put in prod then


Ethan
:orphmoji-yay:  8:40 PM
DATABASE_URL="postgres://postgres:GhvyWgpWdigdiwRmJ5gngVJ6U49Y8AiDauwsXnjfNNc1XCRIZEDHHs3uZvdhQJC1@5.161.100.52:9846/postgres"
PGDATABASE="neondb"
PGHOST="5.161.100.52"
PGPORT="5432"
PGUSER="postgres"
PGPASSWORD="GhvyWgpWdigdiwRmJ5gngVJ6U49Y8AiDauwsXnjfNNc1XCRIZEDHHs3uZvdhQJC1"
GITHUB_CLIENT_ID="Ov23liPtaMsNRLw66vxr"
GITHUB_CLIENT_SECRET="6727f41bec7ddeef2d0fe2638b0cb7780fa84706"
SLACK_CLIENT_ID="2210535565.8465855857699"
SLACK_CLIENT_SECRET="3bc9cf4b47843d2157255e0f4eb0f44c"
SLACK_REDIRECT_URI="https://spaces.learnwillow.org/api/slack/callback"
GITHUB_CALLBACK_URL="https://spaces.hackclub.com/api/github/callback"
GROQ_API_KEY="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"


msw
  8:41 PM
we don't set the DATABASE_URL, the prod environment automatically sets that
8:41
that also means you can't have PGPASSWORD etc set in your env vars
8:41
coolify will automatically set DATABASE_URL in prod for you, but it might change at a moment's notice


Ethan
:orphmoji-yay:  8:41 PM
oh alright


msw
  8:42 PM
cool if i merge https://github.com/hackclub/spaces/pull/6?
#6 Switch to uv and docker
<https://github.com/hackclub/spaces|hackclub/spaces>hackclub/spaces | Mar 30th | Added by GitHub
:+1:
1



Ethan
:orphmoji-yay:  8:42 PM
as long as when the app calls DATABASE_URL, PGHOST, PGPORT, PGPORT and PGUSER it gets the correct values


msw
  8:43 PM
you have to do that in your code– most database adapters will have a way to read DATABASE_URL and automatically parse out all the needed details
8:43
which database library are you using


Ethan
:orphmoji-yay:  8:44 PM
SQLAlchemy
8:44
(Flask-SQLAlchemy)


msw
  8:45 PM
looks like you can just
app.config['SQLALCHEMY_DATABASE_URI'] = DB_URL
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False # silence the deprecation warning

db = SQLAlchemy(app)
8:45
https://vsupalov.com/flask-sqlalchemy-postgres/
vsupalov.comvsupalov.com
Using SQLAlchemy with Flask to Connect to PostgreSQL
Connecting to PostgreSQL from a Flask app, and defining models.
Aug 1st, 2017
8:45
haven't tried it, but that's what this blogpost is saying


Ethan
:orphmoji-yay:  8:45 PM
Alright, i'll test it out
8:46
still trying to get the db migrated over
8:46
it doesnt like that the new db doesnt have ssl


msw
  8:46 PM
turning off the db so i can add ssl
:sparkling_heart:
1

8:47
try again?


Ethan
:orphmoji-yay:  8:48 PM

Connecting to destination database...
Error: connection to server at "5.161.100.52", port 9846 failed: Connection refused
    Is the server running on that host and accepting TCP/IP connections?
8:48
maybe i should give it a sec
8:48
since you just restarted


msw
  8:49 PM
hmmmm... looks like there's an issue with ssl


Ethan
:orphmoji-yay:  8:49 PM
Connecting to source database...
Successfully connected to source database!

Connecting to destination database...
Error: connection to server at "5.161.100.52", port 9846 failed: server does not support SSL, but SSL was required


msw
  8:49 PM
i'm turning it off– you should run without it in prod. it's fine because we're connecting from the machine to itself, so ssl isn't required anyways


Ethan
:orphmoji-yay:  8:49 PM
alright sounds good!


msw
  8:50 PM
for local dev, ideally you could have an ssl connection to the db, but as long as you only connect from your home wifi and places you trust it's fine


Ethan
:orphmoji-yay:  8:50 PM
as long as its not exposed
8:50
or the url doesnt get shared


msw
  8:55 PM
got it working locally with another small change & that env var– will submit a new PR
Screenshot 2025-03-30 at 20.55.26.png
 
Screenshot 2025-03-30 at 20.55.26.png


Ethan
:orphmoji-yay:  8:56 PM
oh cool
8:56
alright
8:56
so i dont need to fix the env variables for the db?


msw
  8:56 PM
nope! fix incoming for that


Ethan
:orphmoji-yay:  8:56 PM
Awesome!!!!! tsym!!


msw
  8:57 PM
https://github.com/hackclub/spaces/pull/8
#8 Fix handling of prod url scheme
<https://github.com/hackclub/spaces|hackclub/spaces>hackclub/spaces | Mar 30th | Added by GitHub


Ethan
:orphmoji-yay:  8:57 PM
trying to migrate now
8:57
you can merge it


msw
  8:57 PM
merged
:+1:
1

8:57
this is the problem i was fixing https://community.render.com/t/sqlalchemy-exc-nosuchmoduleerror-cant-load-plugin-sqlalchemy-dialects-postgres/11789
Render
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
I’m getting this error from SQLAlchemy: sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres turns out, the DB URL generated by Render is an obsolete one — now postgres: is deprecated, and should use postgresql: instead. Context: python - sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres - Stack Overflow Will you fix this soon?
Reading time
1 mins :clock2:
Likes
4 :heart:
May 8th, 2023


Ethan
:orphmoji-yay:  8:57 PM
awesome!


msw
  8:57 PM
i'll redeploy on coolify in a sec


Ethan
:orphmoji-yay:  8:57 PM
alr


msw
  8:58 PM
what's your uptime route?


Ethan
:orphmoji-yay:  8:58 PM
/up
:sparkling_heart:
1

9:01
everything should be migrated over
9:01
i'm going to test it though rn


msw
  9:02 PM
ooops, i didn't hit save on the env vars– redeploying
9:05
oh, also forgot to include these https://github.com/hackclub/spaces/pull/9
#9 Add curl/wget to dockerfile
This is to fix the coolify healthcheck
<https://github.com/hackclub/spaces|hackclub/spaces>hackclub/spaces | Mar 30th | Added by GitHub
:upvote:
1

9:05
coolify needs them to test if new deploys are up


Ethan
:orphmoji-yay:  9:05 PM
turns out the migration didnt copy over a table, redoing


msw
  9:07 PM
we're up https://tk04gow8084cswkkwws0cw4w.a.selfhosted.hackclub.com
9:08
I have https://github.com/hackclub/dns/pull/1633 ready for merge
#1633 Switch spaces.hackclub.com to coolify
This is a draft for now while the coolify deploy is being setup
<https://github.com/hackclub/dns|hackclub/dns>hackclub/dns | Mar 25th | Added by GitHub
9:08
is it cool if i merge this?


Ethan
:orphmoji-yay:  9:08 PM
yep!
9:08
ooh we get an error when trying to log in :yahoo-sigh: https://tk04gow8084cswkkwws0cw4w.a.selfhosted.hackclub.com/login


msw
  9:09 PM
can i get a preview code?

3 replies
Last reply 1 day agoView thread


Ethan
:orphmoji-yay:  9:09 PM
does the deployment update whenever the main branch in the repo changes?


msw
  9:09 PM
or a screenshot?


Ethan
:orphmoji-yay:  9:09 PM
iloveboba


msw
  9:09 PM
it does! deploys take about 2 min, so it's a little delayed
:sparkling_heart:
1

9:10
the env vars give you the current commit if you want to display it– this is how hackatime.hackclub.com has it's version in the footer: https://coolify.io/docs/knowledge-base/environment-variables#source-commit
coolify.iocoolify.io
Coolify Docs
Self hosting with superpowers: An open-source & self-hostable Heroku / Netlify / Vercel alternative. (35 kB)
https://coolify.io/docs/knowledge-base/environment-variables#source-commit



Ethan
:orphmoji-yay:  9:11 PM
nice


msw
  9:11 PM
yeah, i get this on signup– let's check the logs
Screenshot 2025-03-30 at 21.11.26.png
 
Screenshot 2025-03-30 at 21.11.26.png


Ethan
:orphmoji-yay:  9:11 PM
something with the db


msw
  9:11 PM
127.0.0.1 - - [31/Mar/2025 01:11:19] "GET /up HTTP/1.1" 200 -
[2025-03-31 01:11:23,412] ERROR in app: Unhandled Exception: {'error_type': 'Database Error', 'error_message': '(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "user_activity_pkey"\nDETAIL:  Key (id)=(2) already exists.\n\n[SQL: INSERT INTO user_activity (activity_type, message, username, timestamp, user_id, site_id) VALUES (%(activity_type)s, %(message)s, %(username)s, %(timestamp)s, %(user_id)s, %(site_id)s) RETURNING user_activity.id]\n[parameters: {\'activity_type\': \'user_registration\', \'message\': \'New user registered: {username}\', \'username\': \'msw\', \'timestamp\': datetime.datetime(2025, 3, 31, 1, 11, 23, 410148), \'user_id\': None, \'site_id\': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)', 'error_details': None, 'file_name': None, 'line_number': None, 'code_snippet': None, 'traceback': '  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request\n    rv = self.dispatch_request()\n         ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/app/app.py", line 547, in signup\n    db.session.commit()\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 599, in commit\n    return self._proxied.commit()\n           ^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2032, in commit\n    trans.commit(_to_root=True)\n  File "<string>", line 2, in commit\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n                ^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1313, in commit\n    self._prepare_impl()\n  File "<string>", line 2, in _prepare_impl\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n                ^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl\n    self.session.flush()\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4353, in flush\n    self._flush(objects)\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush\n    with util.safe_reraise():\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4449, in _flush\n    flush_context.execute()\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute\n    rec.execute(self)\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute\n    util.preloaded.orm_persistence.save_obj(\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj\n    _emit_insert_statements(\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements\n    result = connection.execute(\n             ^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1416, in execute\n    return meth(\n           ^^^^^\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection\n    return connection._execute_clauseelement(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement\n    ret = self._execute_context(\n          ^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context\n    return self._exec_single_context(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context\n    self._handle_dbapi_exception(\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context\n    self.dialect.do_execute(\n  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 945, in do_execute\n    cursor.execute(statement, parameters)\n', 'suggestions': ['Verify database connection settings', 'Check for invalid queries or constraints', 'Ensure all required fields are provided']}
172.18.0.84 - - [31/Mar/2025 01:11:23] "POST /signup HTTP/1.1" 0 -
127.0.0.1 - - [31/Mar/2025 01:11:24] "GET /up HTTP/1.1" 200 -
127.0.0.1 - - [31/Mar/2025 01:11:29] "GET /up HTTP/1.1" 200 -
127.0.0.1 - - [31/Mar/2025 01:11:34] "GET /up HTTP/1.1" 200 -
127.0.0.1 - - [31/Mar/2025 01:11:39] "GET /up HTTP/1.1" 200 -
127.0.0.1 - - [31/Mar/2025 01:11:44] "GET /up HTTP/1.1" 200 -


Ethan
:orphmoji-yay:  9:12 PM
yeah


msw
  9:12 PM
looks like an id collision


Ethan
:orphmoji-yay:  9:12 PM
migrations always mess up
9:12
yeah checking rn


Ethan
:orphmoji-yay:  9:17 PM
yeah its a migration issue
9:20
when you tested locally with the new db_url thing (from the blog post), did you test login?


msw
  9:21 PM
nope! i didn't want to break anything by creating records
9:21
i just loaded the page to see if the db adapter would boot, then shut it down


Ethan
:orphmoji-yay:  9:21 PM
  Warning: Could not reset sequence for user: COALESCE types text and integer cannot be matched
LINE 2: ...                 SELECT COALESCE(MAX("slack_id"), 0) + 1 FRO...
                                                             ^
9:21
yeah i think this is the issue


msw
  9:22 PM
do you have a psql client locally?


Ethan
:orphmoji-yay:  9:22 PM
ruh roh
9:22
image.png
 
image.png
9:22
its down for users


msw
  9:22 PM
that's fine– just ignore that. let's focus on getting this live
9:23
redeploying prod so the custom domain is updated
9:24
if you don't have a psql client, download beekeeper studio or one of the other free clients
9:24
and connect to the prod db to inspect what's going on


Ethan
:orphmoji-yay:  9:24 PM
yeah i'm doing that rn
9:24
i'm going to rollback
9:24
i prob broke something


msw
  9:24 PM
rollback what?


Ethan
:orphmoji-yay:  9:25 PM
the old db
9:25
which I am migrating from


msw
  9:25 PM
just hang tight


Ethan
:orphmoji-yay:  9:25 PM
?


msw
  9:25 PM
you mean move back to prod using the old db?


Ethan
:orphmoji-yay:  9:25 PM
no


msw
  9:25 PM
oh, the schema


Ethan
:orphmoji-yay:  9:25 PM
restoring a backup
9:26
of the old db
9:26
if that was the issue


msw
  9:26 PM
you already have a backup though, right?


Ethan
:orphmoji-yay:  9:26 PM
yeah
9:26
neondb backs up every second (edited) 
9:26
gotta be careful cause the new db prob doesnt do that


msw
  9:27 PM
we can configure auto backups. i set it up for once per day, but we can make that more often
9:27
if neon handles that already, let's not bother
9:27
just get the new prod working– it'll be down for users for 15 min & that's fine


Ethan
:orphmoji-yay:  9:28 PM
k ima try migration again with the reverted version


msw
  9:28 PM
on the prod db in coolify? (edited) 


Ethan
:orphmoji-yay:  9:29 PM
Migrating the reverted old db to prod db on coolify


msw
  9:29 PM
go for it!


Ethan
:orphmoji-yay:  9:37 PM
ok, i migrated everything over again and I still get errors.
with bookkeeper studio, do you know if you can migrate databases over from there?


msw
  9:38 PM
haven't used it so I can't say. what errors are you running into?
9:38
does your sql adapter keep a schema file?


Ethan
:orphmoji-yay:  9:38 PM
PendingRollbackError
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "user_activity_pkey"
DETAIL:  Key (id)=(236) already exists.

[SQL: INSERT INTO user_activity (activity_type, message, username, timestamp, user_id, site_id) VALUES (%(activity_type)s, %(message)s, %(username)s, %(timestamp)s, %(user_id)s, %(site_id)s) RETURNING user_activity.id]
[parameters: {'activity_type': 'user_login', 'message': 'User {username} logged in', 'username': 'EthanAtHackClub', 'timestamp': datetime.datetime(2025, 3, 31, 1, 35, 55, 843162), 'user_id': 149, 'site_id': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)

Traceback (most recent call last)
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
self.dialect.do_execute(
^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 945, in do_execute
cursor.execute(statement, parameters)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The above exception was the direct cause of the following exception:
File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/app.py", line 307, in decorated_function
return f(*args, **kwargs)
       ^^^^^^^^^^^^^^^^^^
File "/app/app.py", line 504, in login
db.session.commit()
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 599, in commit
return self._proxied.commit()
       ^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
trans.commit(_to_root=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<string>", line 2, in commit
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
ret_value = fn(self, *arg, **kw)
            ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
self._prepare_impl()
^^^^^^^^^^^^^^^^^^^^
File "<string>", line 2, in _prepare_impl
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
ret_value = fn(self, *arg, **kw)
            ^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
self.session.flush()
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4353, in flush
self._flush(objects)
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
with util.safe_reraise():
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
raise exc_value.with_traceback(exc_tb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4449, in _flush
flush_context.execute()
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
rec.execute(self)
^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
util.preloaded.orm_persistence.save_obj(
^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
_emit_insert_statements(
^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
result = connection.execute(
         
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
return meth(
       
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
return connection._execute_clauseelement(
       
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
ret = self._execute_context(
      
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
return self._exec_single_context(
       
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
self._handle_dbapi_exception(
^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
self.dialect.do_execute(
^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 945, in do_execute
cursor.execute(statement, parameters)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 759, in handle_user_exception
return self.ensure_sync(handler)(e)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/app.py", line 180, in handle_error
return render_template('errors/generic.html', **context), code
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
return _render(app, template, context)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
rv = template.render(context)
     ^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
self.environment.handle_exception()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
raise rewrite_traceback_stack(source=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/templates/errors/generic.html", line 1, in top-level template code
{% extends "errors/base_error.html" %}
File "/app/templates/errors/base_error.html", line 1, in top-level template code
{% extends "base.html" %}
File "/app/templates/base.html", line 32, in top-level template code
{% if current_user.is_authenticated %}
File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 490, in getattr
return getattr(obj, attribute)
       ^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/flask_login/mixins.py", line 17, in is_authenticated
return self.is_active
       ^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
return self.impl.get(state, dict_)  # type: ignore[no-any-return]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
value = self._fire_loader_callables(state, key, passive)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
return state._load_expired(state, passive)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state.py", line 803, in _load_expired
self.manager.expired_attribute_loader(self, toload, passive)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 1670, in load_scalar_attributes
result = load_on_ident(
         
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 509, in load_on_ident
return load_on_pk_identity(
       
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 694, in load_on_pk_identity
session.execute(
^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
return self._execute_internal(
       
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2241, in _execute_internal
conn = self._connection_for_bind(bind)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2110, in _connection_for_bind
return trans._connection_for_bind(engine, execution_options)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<string>", line 2, in _connection_for_bind
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
self._raise_for_prerequisite_state(fn.__name__, current_state)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 973, in _raise_for_prerequisite_state
raise sa_exc.PendingRollbackError(
^
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "user_activity_pkey"
DETAIL: Key (id)=(236) already exists.

[SQL: INSERT INTO user_activity (activity_type, message, username, timestamp, user_id, site_id) VALUES (%(activity_type)s, %(message)s, %(username)s, %(timestamp)s, %(user_id)s, %(site_id)s) RETURNING user_activity.id]
[parameters: {'activity_type': 'user_login', 'message': 'User {username} logged in', 'username': 'EthanAtHackClub', 'timestamp': datetime.datetime(2025, 3, 31, 1, 35, 55, 843162), 'user_id': 149, 'site_id': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it.

Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
9:39
i'll check


msw
  9:41 PM
it looks like the issue is that there's already a user with that ID– seems like your migrations shouldn't be applied, right?
9:41
can you link me the migration that's failing?
9:42
when do your mgirations run?


Ethan
:orphmoji-yay:  9:43 PM
I just used db migrator. I'm going to try with bookkeeper though
9:43
cause I am almost certain the migration is the culprit


msw
  9:47 PM
well, check out the error– it's saying the migration is failing because that user already exists. what if you drop the prod data, then run the migrations to setup the schema on an empty database, then port over the data


msw
  9:57 PM
any luck?


Ethan
:orphmoji-yay:  9:57 PM
nope... trying one more thing
9:57
then i need to go to bed


Ethan
:orphmoji-yay:  10:16 PM
image.png
 
image.png
10:16
yeah i dont know what the heck is happening
10:16
i'm going to bed


msw
  10:17 PM
ah, so the neondb is also erroring?
10:17
do you need the latest migration?


Ethan
:orphmoji-yay:  10:17 PM
yeah everything is erroring when transferring over


msw
  10:17 PM
can you link me that file?


Ethan
:orphmoji-yay:  10:17 PM
what file


msw
  10:17 PM
your migration file


Ethan
:orphmoji-yay:  10:18 PM
it didnt make a migration file


msw
  10:18 PM
how are you migrating the data then?


Ethan
:orphmoji-yay:  10:18 PM
it just said migrating between databases


msw
  10:18 PM
what is 'it'?


Ethan
:orphmoji-yay:  10:18 PM
pgAdmin4
10:18
and Bookkeeper studio


msw
  10:18 PM
ooooh, gotcha!


Ethan
:orphmoji-yay:  10:19 PM
wait you can do this with commands??????


msw
  10:19 PM
there are tools like that, but normally for migrations like this i like to write my own thing or use commands


Ethan
:orphmoji-yay:  10:19 PM
oh wait fr


msw
  10:19 PM
is neondb a sql variant?


Ethan
:orphmoji-yay:  10:19 PM
yeah its postgres
10:19
Old DB: postgresql://neondb_owner:npg_zyvpAYX5oi0k@ep-ancient-hill-a6yb7my6.us-west-2.aws.neon.tech/neondb?sslmode=require
New DB: postgres://postgres:GhvyWgpWdigdiwRmJ5gngVJ6U49Y8AiDauwsXnjfNNc1XCRIZEDHHs3uZvdhQJC1@5.161.100.52:9846/postgres


msw
  10:19 PM
perf! https://neon.tech/docs/import/migrate-from-postgres
NeonNeon
Migrate data from Postgres with pg_dump and pg_restore - Neon Docs
This topic describes migrating data from one Postgres database to another using the pg_dump and pg_restore. Avoid using pg_dump over a pooled connection string (see PgBouncer issues 452 & 976 for deta... (303 kB)
https://neon.tech/docs/import/migrate-from-postgres

10:19
pg has a built in command for dumping all your db records and pushing them to a database
10:20
it's more made for restoring from backups, but we can use it to transfer the data


Ethan
:orphmoji-yay:  10:20 PM
oh alright
10:23
~/workspace$ pg_dump "postgresql://neondb_owner:npg_zyvpAYX5oi0k@ep-ancient-hill-a6yb7my6.us-west-2.aws.neon.tech/neondb?sslmode=require&options=endpoint%3Dep-ancient-hill-a6yb7my6" | psql "postgres://postgres:GhvyWgpWdigdiwRmJ5gngVJ6U49Y8AiDauwsXnjfNNc1XCRIZEDHHs3uZvdhQJC1@5.161.100.52:9846/postgres"
SET
SET
SET
SET
SET
 set_config 
------------
 
(1 row)

SET
SET
SET
SET
CREATE FUNCTION
ERROR:  role "neondb_owner" does not exist
CREATE FUNCTION
ERROR:  role "neondb_owner" does not exist
CREATE FUNCTION
ERROR:  role "neondb_owner" does not exist
SET
SET
CREATE TABLE
ERROR:  role "neondb_owner" does not exist
ERROR:  relation "club_id_seq" already exists
ERROR:  role "neondb_owner" does not exist
ALTER SEQUENCE
CREATE TABLE
ERROR:  role "neondb_owner" does not exist
ERROR:  relation "club_member_id_seq" already exists
ERROR:  role "neondb_owner" does not exist
ALTER SEQUENCE
CREATE TABLE
ERROR:  role "neondb_owner" does not exist
ERROR:  relation "club_membership_id_seq" already exists
ERROR:  role "neondb_owner" does not exist
ALTER SEQUENCE
CREATE TABLE
ERROR:  role "neondb_owner" does not exist
ERROR:  relation "github_repo_id_seq" already exists
ERROR:  role "neondb_owner" does not exist
ALTER SEQUENCE
CREATE TABLE
ERROR:  role "neondb_owner" does not exist
ERROR:  relation "site_id_seq" already exists
ERROR:  role "neondb_owner" does not exist
ALTER SEQUENCE
CREATE TABLE
ERROR:  role "neondb_owner" does not exist
ERROR:  relation "site_page_id_seq" already exists
ERROR:  role "neondb_owner" does not exist
ALTER SEQUENCE
CREATE TABLE
ERROR:  role "neondb_owner" does not exist
CREATE TABLE
ERROR:  role "neondb_owner" does not exist
CREATE TABLE
ERROR:  role "neondb_owner" does not exist
ERROR:  relation "user_activity_id_seq" already exists
ERROR:  role "neondb_owner" does not exist
ALTER SEQUENCE
ERROR:  relation "user_id_seq" already exists
ERROR:  role "neondb_owner" does not exist
ALTER SEQUENCE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
COPY 7
COPY 0
COPY 7
COPY 23
COPY 94
COPY 267
COPY 1
COPY 128
COPY 856
 setval 
--------
     25
(1 row)

 setval 
--------
      3
(1 row)

 setval 
--------
     21
(1 row)

 setval 
--------
     57
(1 row)

 setval 
--------
    232
(1 row)

 setval 
--------
   1709
(1 row)

 setval 
--------
    858
(1 row)

 setval 
--------
    154
(1 row)

ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
CREATE INDEX
CREATE INDEX
CREATE TRIGGER
CREATE TRIGGER
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ERROR:  role "neon_superuser" does not exist
ERROR:  role "neon_superuser" does not exist
~/workspace$ 
10:23
just did this command
10:23
seems like it did something
10:24
image.png
 
image.png
10:24
YAY!!!!!
10:24
it works!!!!!!!!!1


Ethan
:orphmoji-yay:  10:30 PM
Ok so coolify works now, can you update the https://spaces.hackclub.com domain and tell me what records to change for the other domains?


msw
  10:30 PM
it's already up – https://spaces.hackclub.com/ is going to coolify


Ethan
:orphmoji-yay:  10:31 PM
oh alright cool!
10:31
what records should I change for the other domains to direct it to coolify


msw
  10:31 PM
wdym?
10:31
just link to spaces.hackclub.com?
10:32
i just logged in– new user is msw


Ethan
:orphmoji-yay:  10:32 PM
for web spaces, when users deploy, I give them a choice of what domain to use
image.png
 
image.png


msw
  10:33 PM
oh, i see. how are those domains currently configured?


Ethan
:orphmoji-yay:  10:33 PM
just with a records in cloudflare pointing towards the replit config


msw
  10:33 PM
gotcha– and how are they currently hosted?


Ethan
:orphmoji-yay:  10:34 PM
they were hosted on replit deployments along with the main url


msw
  10:34 PM
like, what prevents hackclub.me/s/df from also be loaded when you go to spaces.hackclub.com/s/df
10:34
cause that would load if you just deployed it from the same server


Ethan
:orphmoji-yay:  10:35 PM
Yeah but I am going to block deploying sites on the hack club domain for obvious reasons and I want to give users a choice


msw
  10:35 PM
i get that, i'm asking about the current infra– what prevents that
10:35
i need to know how your routing works to figure out how we can do this with coolify


Ethan
:orphmoji-yay:  10:35 PM
ohh


msw
  10:36 PM
cause it should work the same as when it was on replit


Ethan
:orphmoji-yay:  10:36 PM
yeah basically all of those domains were configured like the spaces.hackclub.com one


msw
  10:36 PM
but the setup you're describing doesn't seem like it prevents people from hosting on spaces.hackclub.com, it just doesn't tell them that they're also hosting there


Ethan
:orphmoji-yay:  10:36 PM
yeah i'm going to add prevention for that, havent done that yet


msw
  10:36 PM
oh, gotcha!
:sparkling_heart:
1



Ethan
:orphmoji-yay:  10:36 PM
because I can detect what domain the user is on


msw
  10:37 PM
yep, do that!
10:37
https://github.com/hackclub/dns/commit/02dd093bfbaad6cd37031212f9be8f5e328973b2
10:37
this is how the routing works– just set it up like this for your other domains & detect where inbound traffic is coming from


Ethan
:orphmoji-yay:  10:38 PM
oh alright so just cname to `a.selfhosted.hackclub.com`?
10:38
or is there anything you need to do coolify-side


msw
  10:39 PM
there's a little bit of config I need to add, but i'll add it whenever you link me a new domain you want to add


Ethan
:orphmoji-yay:  10:39 PM
Alright, i'll do that tommorow
10:39
everything should be working now though
10:40
thanks for all of the help by the way, i've learned a ton!


Ethan
:orphmoji-yay:  8:53 PM
A CNAME record pointing to a.selfhosted.hackclub.com has been made for all of the following domains,
Can they be added to the deployment on Coolify?
hackclub.me
hackclub.space
imahacker.lol
myhack.club


msw
  9:41 PM
added!


Ethan
:orphmoji-yay:  9:41 PM
awesome!
9:41
how frequently does a heartbeat need to be sent?
like once every 30 sec?
9:42
cause it registers the heartbeats but not the time
image.png
 
image.png
9:42
(made this super nice ui)
image.png
 
image.png
:sparkling_heart:
1
:yay:
1



msw
  10:17 PM
don't do it on a timer, do it based on user action
10:17
like, if someone isn't touching anything it shouldn't be emitting heartbeats
10:17
but for a file save, edits, etc.
10:17
i really like that interface!


Ethan
:orphmoji-yay:  10:28 PM
Yep it tracks when the user is idle
10:28
so the more heartbeats the better?
10:28
and we dont track time?
10:31
because how its setup currently is it detects file changes, file saves, edits and if its consistently getting that, sends a heartbeat every 30 secs.
10:31
if its not, it pauses and doesnt send anything (edited) 


msw
  10:57 PM
yeah! you can use the bulk upload endpoint to send multiple


Ethan
:orphmoji-yay:  11:09 PM
ok cool! so just to be clear, hackatime doesnt track time at all anymore and just does heartbeats? Sorry, this is so confusing to me


msw
  11:09 PM
it always only tracked heartbeats!
11:09
even wakatime.com just tracks heartbeats


Ethan
:orphmoji-yay:  11:10 PM
wait then how does it get the time :sob:


msw
  11:11 PM
under the hood it does some math on every heartbeat saying "oh, this user had a heartbeat at 9:32:15 & a heartbeat at 9:33:04, so we'll bridge the gap and call it 49 sec of work"


Ethan
:orphmoji-yay:  11:11 PM
ohhhhhhhh
11:11
so sending a heartbeat every 30 sec while the user is active and coding is fine
11:12
I understand now, thanks!!!


msw
  11:12 PM
that's fine, but the more accurate the better!


Ethan
:orphmoji-yay:  11:12 PM
i'm making it super accurate!!!
11:12
what stops people from making bots that just send a heartbeat every few secs


msw
  11:12 PM
https://github.com/hackclub/harbor/blob/41ea56dac9bc224fe65285e3158a5db15fd056d6/app/models/concerns/heartbeatable.rb#L129-L144
we have some very efficient code in here that can do that math really really quickly
heartbeatable.rb
        capped_diffs = scope
          .select("#{group_expr} as grouped_time, CASE
            WHEN LAG(time) OVER (PARTITION BY #{group_expr} ORDER BY time) IS NULL THEN 0
            ELSE LEAST(EXTRACT(EPOCH FROM (to_timestamp(time) - to_timestamp(LAG(time) OVER (PARTITION BY #{group_expr} ORDER BY time)))), #{heartbeat_timeout_duration.to_i})
          END as diff")
Show more
<https://github.com/hackclub/harbor|hackclub/harbor>hackclub/harbor | Added by GitHub

1 reply
17 hours agoView thread


msw
  11:13 PM
so every time you load the page on hackatime.hackclub.com & it says your time, it's actually adding up the times between 100s, 100ks, or millions of heartbeats in under a second (edited) 


Ethan
:orphmoji-yay:  11:13 PM
oh wow
11:14
wait how come it doesnt show me a time
11:14
when i have like 90


msw
  11:14 PM
people can totally bot hackatime, that's why it's important to get detailed stats about what the user did

1 reply
17 hours agoView thread


msw
  11:15 PM
most people who try to cheat their time are lazy, so they do lazy things like emit a heartbeat every 30 sec, or have the heartbeat choose between like 3 & 5 over and over and over


Ethan
:orphmoji-yay:  11:15 PM
and i guess it wouldnt have data attached to it either
11:15
of the work


msw
  11:15 PM
while that's not an indicator of being a bot if someone does that a little, a whole day of just emitting heartbeats every 30 sec, or editing the same new lines is a sign

1 reply
17 hours agoView thread


Ethan
:orphmoji-yay:  11:15 PM
like I'm currently sending the file they are on and the current line


msw
  11:16 PM
no, bots can fake that– line num, file name, additions, user agent (edited) 
11:16
it's all spoofable


Ethan
:orphmoji-yay:  11:16 PM
yeah but people wouldnt be developing for like 50 hours straight
:+1:
1



msw
  11:16 PM
the only thing we can do is analyze the data and find patterns. that's why it's so important you're sending as detailed data as you can.


Ethan
:orphmoji-yay:  11:17 PM
yeah thats smart!! tsym!
11:17
how long does it take for the time to update
11:18
cause I was just testing hackatime with spaces, it sent like 10 heartbeats over the span of 5 min
11:18
and the time didnt get updated
11:18
does that just like take a bit?


msw
  11:18 PM
oh! one other part of the time calculation is a TIMEOUT_INTERVAL
11:18
so if you emit a heartbeat at 10:35:01 & at 10:35:10, I'll bridge that and call it 9 sec of work


Ethan
:orphmoji-yay:  11:19 PM
oh alright so I might need to send them more consistantly


msw
  11:19 PM
but if you emit a heartbeat at 10:35:01 & then another at 11:01:30, i'm not going to say "oh, you worked for 25 min"


Ethan
:orphmoji-yay:  11:19 PM
yeah


msw
  11:19 PM
yeah– the timeout interval on hackatime is 2 min– if your heartbeats are any longer then that they don't get bridged


Ethan
:orphmoji-yay:  11:19 PM
hm thats weird


msw
  11:19 PM
but if someone stops coding for 2 min you shouldn't emit heartbeats!


10 replies
Last reply 17 hours agoView thread


Ethan
:orphmoji-yay:  11:20 PM
i set it as 30 sec


msw
  11:20 PM
I can check them– one sec
11:20
are you setting the time field?
11:20
I don't see you on the leaderboard


Ethan
:orphmoji-yay:  11:20 PM
hmmm
11:20
let me check


msw
  11:23 PM
can you send me the link to the Stats badges on hackatime.hackclub.com/my/settings?
11:23
i can use that to pull your heartbeat data


Ethan
:orphmoji-yay:  11:24 PM
https://github-readme-stats.hackclub.dev/api/wakatime?username=18&api_domain=hackatime.hackclub.com&theme=darcula&custom_title=Hackatime+Stats&layout=compact&cache_seconds=0&langs_count=8
11:24
this?
11:24
 heartbeat_data = [{
            'type': data.get('type', 'file'),
            'time': data.get('time', int(time.time())),
            'entity': data.get('entity', 'unknown'),
            'language': data.get('language', 'Text'),
            'is_write': data.get('is_write', True)
        }]
11:24
found it
11:24
so this is whats tracked and sent


msw
  11:25 PM
perf, thanks!
11:25
ah, you're missing a couple fields there


Ethan
:orphmoji-yay:  11:25 PM
oh alright!
11:26
which ones?


msw
  11:27 PM
project
user_agent
lineno
line_additions
etc.
11:27
https://github.com/hackclub/harbor/blob/41ea56dac9bc224fe65285e3158a5db15fd056d6/app/controllers/api/hackatime/v1/hackatime_controller.rb#L108-L127
hackatime_controller.rb
      :branch,
      :category,
      :created_at,
      :cursorpos,
      :dependencies,
Show more
<https://github.com/hackclub/harbor|hackclub/harbor>hackclub/harbor | Added by GitHub


Ethan
:orphmoji-yay:  11:27 PM
wait i need all of that?


msw
  11:28 PM
check out https://wakatime.com/developers#heartbeats for an example
WakaTimeWakaTime
WakaTime API Docs
Developer reference documentation for the WakaTime API.


Ethan
:orphmoji-yay:  11:28 PM
ahhhhhh thats a lot of data
11:28
i'll figure it out


msw
  11:28 PM
oh yeah, it's a bunch!
11:28
for the most part though, this isn't anything too crazy– just include the line numbers and hard code the stuff you can't include for now


Ethan
:orphmoji-yay:  11:29 PM
yeah i am not finishing this thing by the deadline of wednesday


msw
  11:29 PM
for example, ua is always gonna be the same!


Ethan
:orphmoji-yay:  11:29 PM
Alright!


msw
  11:29 PM
cut the corners you need to cut– get a thing done by wed
:+1:
1



Ethan
:orphmoji-yay:  11:30 PM
yeah its launching officially friday
11:30
doing security testing thursday


Ethan
:orphmoji-yay:  3:40 PM
 heartbeat_data = [{
            'type': data.get('type', 'file'),
            'time': data.get('time', time.time()),
            'entity': data.get('entity', 'unknown'),
            'category': data.get('category', 'coding'),
            'project': data.get('project', 'Unknown Project'),
            'project_root_count': data.get('project_root_count', 2),
            'branch': data.get('branch', 'main'),
            'language': data.get('language', 'Text'),
            'dependencies': data.get('dependencies', 'spaces'),
            'lines': data.get('lines', 0),
            'line_additions': data.get('line_additions', 10),
            'line_deletions': data.get('line_deletions', 5),
            'lineno': data.get('lineno', 1),
            'cursorpos': data.get('cursorpos', 1),
            'is_write': data.get('is_write', True)
        }]
Did I miss anything? Its still not logging time


2 replies
Last reply today at 4:01 PMView thread


Ethan
:orphmoji-yay:  3:45 PM
Rushil just told me about the meeting! What do you mean about focusing on building things? I have?